### ISSUE TITLE
Call API : HTTP Error 400

### ISSUE THREAD

**Issue by MilesTEG1** [turbosnute/netatmo-influxdb#1]
Hello,
I've got some troubles to have your image working on my Docker.
I successfully build the container in my Docker instance (on a Synology DS920+).
I've got a running influxDB (and Telegraf + Grafana + Chronograf) containers. I create a database on influxDB named netatmo.
When I run the netatmo-influxdb container, I've got this :

````log
Thu Oct 29 18:11:33 UTC 2020
--- Start Call API
Traceback (most recent call last):
  File "netatmo2influxdb.py", line 35, in <module>
    authorization = lnetatmo.ClientAuth(clientId=netatmo_clientId,
  File "/lnetatmo.py", line 83, in __init__
    resp = postRequest(_AUTH_REQ, postParams)
  File "/lnetatmo.py", line 508, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400:
Exit status not 0
Sleep 120
Thu Oct 29 18:13:33 UTC 2020
Sleep 60
````

I tried to change the database user / password to those I defined to admin, but I still have this : 

````log
Thu Oct 29 18:19:37 UTC 2020,
--- Start Call API,
Traceback (most recent call last):,
  File "netatmo2influxdb.py", line 35, in <module>,
    authorization = lnetatmo.ClientAuth(clientId=netatmo_clientId,,
  File "/lnetatmo.py", line 83, in __init__,
    resp = postRequest(_AUTH_REQ, postParams),
  File "/lnetatmo.py", line 508, in postRequest,
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8"),
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen,
    return opener.open(url, data, timeout),
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open,
    response = meth(req, response),
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response,
    response = self.parent.error(,
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error,
    return self._call_chain(*args),
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain,
    result = func(*args),
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default,
    raise HTTPError(req.full_url, code, msg, hdrs, fp),
urllib.error.HTTPError: HTTP Error 400: ,
Exit status not 0,

0,
````

I see that Netatmo has changed their API to grab the data since the last time I worked on a different project using this API.
Maybe your app use an old API no more working...

Thanks for your help.

**Comment by turbosnute** [comment]
I'm sorry that I didn't see your issue until now. I sill get data from netatmo through this API. Are you sure you set all the environment variables and have a active api key?
